#version: '3.9'                # versão do formato que estamos usando

services:                      # serviços que vão subir
  api-backend:                 # nome do servico/container
    build: ./backend           # onde esta o dockerfile na apsta ./back
    container_name: s_back     # nome do containner
    volumes:                   # mapeamento de pastas entre meu pc e o containner
      - ./backend:/app                # ./ pasta no meu pc onde esta o docker-compose
    ports:                     # /app pasta dentro do containner
      - "3001:3001"            # porta do windows : porta dentro do containner

  web-frontend:
    build: ./frontend          # pasta que esta o dockerfile
    container_name: s_front
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - api-backend            # front só liga depois que o back estiver pronto        